"""
NIFTY 500 Stock Universe
Complete list of NIFTY 500 constituent stocks for the Swing Trading Scanner.
"""

NIFTY_500_STOCKS = [
    # ── NIFTY 50 (Large Cap — Top 50) ──────────────────────────────────
    ("RELIANCE.NS", "Reliance Industries", "Conglomerate", "NSE"),
    ("TCS.NS", "Tata Consultancy Services", "IT", "NSE"),
    ("HDFCBANK.NS", "HDFC Bank", "Banking", "NSE"),
    ("INFY.NS", "Infosys", "IT", "NSE"),
    ("ICICIBANK.NS", "ICICI Bank", "Banking", "NSE"),
    ("BHARTIARTL.NS", "Bharti Airtel", "Telecom", "NSE"),
    ("SBIN.NS", "State Bank of India", "Banking", "NSE"),
    ("ITC.NS", "ITC", "FMCG", "NSE"),
    ("LT.NS", "Larsen & Toubro", "Infrastructure", "NSE"),
    ("HINDUNILVR.NS", "Hindustan Unilever", "FMCG", "NSE"),
    ("KOTAKBANK.NS", "Kotak Mahindra Bank", "Banking", "NSE"),
    ("BAJFINANCE.NS", "Bajaj Finance", "NBFC", "NSE"),
    ("AXISBANK.NS", "Axis Bank", "Banking", "NSE"),
    ("WIPRO.NS", "Wipro", "IT", "NSE"),
    ("HCLTECH.NS", "HCL Technologies", "IT", "NSE"),
    ("MARUTI.NS", "Maruti Suzuki", "Auto", "NSE"),
    ("SUNPHARMA.NS", "Sun Pharma", "Pharma", "NSE"),
    ("ASIANPAINT.NS", "Asian Paints", "Paints", "NSE"),
    ("BAJAJFINSV.NS", "Bajaj Finserv", "Financial Services", "NSE"),
    ("TITAN.NS", "Titan Company", "Consumer Durables", "NSE"),
    ("NTPC.NS", "NTPC", "Power", "NSE"),
    ("ONGC.NS", "ONGC", "Oil & Gas", "NSE"),
    ("M&M.NS", "Mahindra & Mahindra", "Auto", "NSE"),
    ("TATAMOTORS.NS", "Tata Motors", "Auto", "NSE"),
    ("POWERGRID.NS", "Power Grid Corp", "Power", "NSE"),
    ("ULTRACEMCO.NS", "UltraTech Cement", "Cement", "NSE"),
    ("ADANIENT.NS", "Adani Enterprises", "Conglomerate", "NSE"),
    ("ADANIPORTS.NS", "Adani Ports", "Infrastructure", "NSE"),
    ("NESTLEIND.NS", "Nestle India", "FMCG", "NSE"),
    ("TATASTEEL.NS", "Tata Steel", "Metals", "NSE"),
    ("JSWSTEEL.NS", "JSW Steel", "Metals", "NSE"),
    ("TECHM.NS", "Tech Mahindra", "IT", "NSE"),
    ("GRASIM.NS", "Grasim Industries", "Diversified", "NSE"),
    ("COALINDIA.NS", "Coal India", "Mining", "NSE"),
    ("HINDALCO.NS", "Hindalco", "Metals", "NSE"),
    ("BRITANNIA.NS", "Britannia Industries", "FMCG", "NSE"),
    ("CIPLA.NS", "Cipla", "Pharma", "NSE"),
    ("DRREDDY.NS", "Dr. Reddy's Labs", "Pharma", "NSE"),
    ("BPCL.NS", "Bharat Petroleum", "Oil & Gas", "NSE"),
    ("EICHERMOT.NS", "Eicher Motors", "Auto", "NSE"),
    ("APOLLOHOSP.NS", "Apollo Hospitals", "Healthcare", "NSE"),
    ("TATACONSUM.NS", "Tata Consumer Products", "FMCG", "NSE"),
    ("DIVISLAB.NS", "Divi's Labs", "Pharma", "NSE"),
    ("SBILIFE.NS", "SBI Life Insurance", "Insurance", "NSE"),
    ("HDFCLIFE.NS", "HDFC Life Insurance", "Insurance", "NSE"),
    ("HEROMOTOCO.NS", "Hero MotoCorp", "Auto", "NSE"),
    ("INDUSINDBK.NS", "IndusInd Bank", "Banking", "NSE"),
    ("BAJAJ-AUTO.NS", "Bajaj Auto", "Auto", "NSE"),
    ("BEL.NS", "Bharat Electronics", "Defence", "NSE"),
    ("HAL.NS", "Hindustan Aeronautics", "Defence", "NSE"),

    # ── NIFTY NEXT 50 (Large Cap — 51-100) ─────────────────────────────
    ("ADANIGREEN.NS", "Adani Green Energy", "Power", "NSE"),
    ("AMBUJACEM.NS", "Ambuja Cement", "Cement", "NSE"),
    ("ACC.NS", "ACC", "Cement", "NSE"),
    ("SHREECEM.NS", "Shree Cement", "Cement", "NSE"),
    ("PIDILITIND.NS", "Pidilite Industries", "Chemicals", "NSE"),
    ("IOC.NS", "Indian Oil Corp", "Oil & Gas", "NSE"),
    ("GAIL.NS", "GAIL India", "Oil & Gas", "NSE"),
    ("VEDL.NS", "Vedanta", "Metals", "NSE"),
    ("NMDC.NS", "NMDC", "Metals", "NSE"),
    ("NATIONALUM.NS", "National Aluminium", "Metals", "NSE"),
    ("SIEMENS.NS", "Siemens", "Capital Goods", "NSE"),
    ("ABB.NS", "ABB India", "Capital Goods", "NSE"),
    ("BHEL.NS", "BHEL", "Capital Goods", "NSE"),
    ("CUMMINSIND.NS", "Cummins India", "Capital Goods", "NSE"),
    ("DLF.NS", "DLF", "Real Estate", "NSE"),
    ("GODREJPROP.NS", "Godrej Properties", "Real Estate", "NSE"),
    ("OBEROIRLTY.NS", "Oberoi Realty", "Real Estate", "NSE"),
    ("PRESTIGE.NS", "Prestige Estates", "Real Estate", "NSE"),
    ("TATAPOWER.NS", "Tata Power", "Power", "NSE"),
    ("SRF.NS", "SRF", "Chemicals", "NSE"),
    ("HAVELLS.NS", "Havells India", "Consumer Durables", "NSE"),
    ("VOLTAS.NS", "Voltas", "Consumer Durables", "NSE"),
    ("CROMPTON.NS", "Crompton Greaves", "Consumer Durables", "NSE"),
    ("WHIRLPOOL.NS", "Whirlpool India", "Consumer Durables", "NSE"),
    ("TRENT.NS", "Trent (Westside)", "Retail", "NSE"),
    ("DMART.NS", "Avenue Supermarts", "Retail", "NSE"),
    ("PAGEIND.NS", "Page Industries", "Textiles", "NSE"),
    ("INDIGO.NS", "InterGlobe Aviation", "Aviation", "NSE"),
    ("IRCTC.NS", "IRCTC", "Travel & Tourism", "NSE"),
    ("ZOMATO.NS", "Zomato", "Internet", "NSE"),
    ("POLICYBZR.NS", "PB Fintech", "Fintech", "NSE"),
    ("NYKAA.NS", "Nykaa", "E-Commerce", "NSE"),
    ("PAYTM.NS", "One97 Communications", "Fintech", "NSE"),
    ("JIOFIN.NS", "Jio Financial Services", "Financial Services", "NSE"),
    ("LICI.NS", "LIC of India", "Insurance", "NSE"),
    ("IDEA.NS", "Vodafone Idea", "Telecom", "NSE"),
    ("DABUR.NS", "Dabur India", "FMCG", "NSE"),
    ("MARICO.NS", "Marico", "FMCG", "NSE"),
    ("COLPAL.NS", "Colgate Palmolive", "FMCG", "NSE"),
    ("GODREJCP.NS", "Godrej Consumer Products", "FMCG", "NSE"),
    ("BIOCON.NS", "Biocon", "Pharma", "NSE"),
    ("LUPIN.NS", "Lupin", "Pharma", "NSE"),
    ("AUROPHARMA.NS", "Aurobindo Pharma", "Pharma", "NSE"),
    ("TORNTPHARM.NS", "Torrent Pharma", "Pharma", "NSE"),
    ("SYNGENE.NS", "Syngene International", "Pharma", "NSE"),
    ("GLENMARK.NS", "Glenmark Pharma", "Pharma", "NSE"),
    ("IPCALAB.NS", "IPCA Labs", "Pharma", "NSE"),
    ("ALKEM.NS", "Alkem Labs", "Pharma", "NSE"),
    ("LAURUSLABS.NS", "Laurus Labs", "Pharma", "NSE"),

    # ── BANKING & FINANCE (101-150) ────────────────────────────────────
    ("PNB.NS", "Punjab National Bank", "Banking", "NSE"),
    ("BANKBARODA.NS", "Bank of Baroda", "Banking", "NSE"),
    ("IDFCFIRSTB.NS", "IDFC First Bank", "Banking", "NSE"),
    ("FEDERALBNK.NS", "Federal Bank", "Banking", "NSE"),
    ("INDIANB.NS", "Indian Bank", "Banking", "NSE"),
    ("CANBK.NS", "Canara Bank", "Banking", "NSE"),
    ("UNIONBANK.NS", "Union Bank", "Banking", "NSE"),
    ("BANDHANBNK.NS", "Bandhan Bank", "Banking", "NSE"),
    ("AUBANK.NS", "AU Small Finance Bank", "Banking", "NSE"),
    ("IDBI.NS", "IDBI Bank", "Banking", "NSE"),
    ("MAHABANK.NS", "Bank of Maharashtra", "Banking", "NSE"),
    ("CENTRALBK.NS", "Central Bank", "Banking", "NSE"),
    ("IOB.NS", "Indian Overseas Bank", "Banking", "NSE"),
    ("UCOBANK.NS", "UCO Bank", "Banking", "NSE"),
    ("BANKSINDIA.NS", "Bank of India", "Banking", "NSE"),
    ("J&KBANK.NS", "J&K Bank", "Banking", "NSE"),
    ("KARURVYSYA.NS", "Karur Vysya Bank", "Banking", "NSE"),
    ("SOUTHBANK.NS", "South Indian Bank", "Banking", "NSE"),
    ("RBLBANK.NS", "RBL Bank", "Banking", "NSE"),
    ("CUB.NS", "City Union Bank", "Banking", "NSE"),
    ("TMB.NS", "Tamilnad Mercantile Bank", "Banking", "NSE"),
    ("DCBBANK.NS", "DCB Bank", "Banking", "NSE"),
    ("BAJAJHLDNG.NS", "Bajaj Holdings", "Financial Services", "NSE"),
    ("CHOLAFIN.NS", "Cholamandalam Finance", "NBFC", "NSE"),
    ("MUTHOOTFIN.NS", "Muthoot Finance", "NBFC", "NSE"),
    ("MANAPPURAM.NS", "Manappuram Finance", "NBFC", "NSE"),
    ("SHRIRAMFIN.NS", "Shriram Finance", "NBFC", "NSE"),
    ("M&MFIN.NS", "Mahindra Finance", "NBFC", "NSE"),
    ("PEL.NS", "Piramal Enterprises", "NBFC", "NSE"),
    ("LICHSGFIN.NS", "LIC Housing Finance", "NBFC", "NSE"),
    ("CANFINHOME.NS", "Can Fin Homes", "NBFC", "NSE"),
    ("PNBHOUSING.NS", "PNB Housing Finance", "NBFC", "NSE"),
    ("IIFL.NS", "IIFL Finance", "NBFC", "NSE"),
    ("MFSL.NS", "Max Financial Services", "Insurance", "NSE"),
    ("SBICARD.NS", "SBI Cards", "Financial Services", "NSE"),
    ("ICICIPRULI.NS", "ICICI Pru Life", "Insurance", "NSE"),
    ("ICICIGI.NS", "ICICI Lombard", "Insurance", "NSE"),
    ("HDFCAMC.NS", "HDFC AMC", "Financial Services", "NSE"),
    ("NAM-INDIA.NS", "Nippon Life AMC", "Financial Services", "NSE"),
    ("CAMS.NS", "CAMS", "Financial Services", "NSE"),
    ("CDSL.NS", "CDSL", "Financial Services", "NSE"),
    ("BSE.NS", "BSE", "Financial Services", "NSE"),
    ("MCX.NS", "Multi Commodity Exchange", "Financial Services", "NSE"),
    ("ANGELONE.NS", "Angel One", "Financial Services", "NSE"),
    ("MOTILALOFS.NS", "Motilal Oswal", "Financial Services", "NSE"),

    # ── IT & TECH (151-200) ────────────────────────────────────────────
    ("LTIM.NS", "LTIMindtree", "IT", "NSE"),
    ("PERSISTENT.NS", "Persistent Systems", "IT", "NSE"),
    ("COFORGE.NS", "Coforge", "IT", "NSE"),
    ("MPHASIS.NS", "Mphasis", "IT", "NSE"),
    ("LTTS.NS", "L&T Technology Services", "IT", "NSE"),
    ("OFSS.NS", "Oracle Financial Services", "IT", "NSE"),
    ("TATAELXSI.NS", "Tata Elxsi", "IT", "NSE"),
    ("HAPPSTMNDS.NS", "Happiest Minds", "IT", "NSE"),
    ("NAUKRI.NS", "Info Edge", "Internet", "NSE"),
    ("INDIAMART.NS", "IndiaMART", "Internet", "NSE"),
    ("MAPMYINDIA.NS", "MapMyIndia", "IT", "NSE"),
    ("DIXON.NS", "Dixon Technologies", "Electronics", "NSE"),
    ("KAYNES.NS", "Kaynes Technology", "Electronics", "NSE"),
    ("CYIENT.NS", "Cyient", "IT", "NSE"),
    ("KPITTECH.NS", "KPIT Technologies", "IT", "NSE"),
    ("ZENSAR.NS", "Zensar Technologies", "IT", "NSE"),
    ("BIRLASOFT.NS", "Birlasoft", "IT", "NSE"),
    ("MASTEK.NS", "Mastek", "IT", "NSE"),
    ("TANLA.NS", "Tanla Platforms", "IT", "NSE"),
    ("ROUTE.NS", "Route Mobile", "IT", "NSE"),
    ("NEWGEN.NS", "Newgen Software", "IT", "NSE"),
    ("INTELLECT.NS", "Intellect Design", "IT", "NSE"),
    ("SONATSOFTW.NS", "Sonata Software", "IT", "NSE"),
    ("TATACOMM.NS", "Tata Communications", "Telecom", "NSE"),
    ("RATEGAIN.NS", "RateGain Travel", "IT", "NSE"),

    # ── PHARMA & HEALTHCARE (201-235) ──────────────────────────────────
    ("ABBOTINDIA.NS", "Abbott India", "Pharma", "NSE"),
    ("MAXHEALTH.NS", "Max Healthcare", "Healthcare", "NSE"),
    ("FORTIS.NS", "Fortis Healthcare", "Healthcare", "NSE"),
    ("METROPOLIS.NS", "Metropolis Healthcare", "Healthcare", "NSE"),
    ("LALPATHLAB.NS", "Dr Lal PathLabs", "Healthcare", "NSE"),
    ("NATCOPHARM.NS", "Natco Pharma", "Pharma", "NSE"),
    ("AJANTPHARM.NS", "Ajanta Pharma", "Pharma", "NSE"),
    ("GRANULES.NS", "Granules India", "Pharma", "NSE"),
    ("AARTIIND.NS", "Aarti Industries", "Pharma", "NSE"),
    ("AARTIDRUGS.NS", "Aarti Drugs", "Pharma", "NSE"),
    ("JBCHEPHARM.NS", "JB Chemicals", "Pharma", "NSE"),
    ("ERIS.NS", "Eris Lifesciences", "Pharma", "NSE"),
    ("SUVEN.NS", "Suven Pharma", "Pharma", "NSE"),
    ("MANKIND.NS", "Mankind Pharma", "Pharma", "NSE"),
    ("CONCORD.NS", "Concord Biotech", "Pharma", "NSE"),
    ("MEDANTA.NS", "Global Health (Medanta)", "Healthcare", "NSE"),
    ("YATHARTH.NS", "Yatharth Hospital", "Healthcare", "NSE"),
    ("RAINBOW.NS", "Rainbow Children's Medicare", "Healthcare", "NSE"),
    ("CLEAN.NS", "Clean Science", "Chemicals", "NSE"),
    ("AETHER.NS", "Aether Industries", "Chemicals", "NSE"),

    # ── AUTO & AUTO ANCILLARY (236-270) ────────────────────────────────
    ("ASHOKLEY.NS", "Ashok Leyland", "Auto", "NSE"),
    ("TATAMTRDVR.NS", "Tata Motors DVR", "Auto", "NSE"),
    ("TVSMOTOR.NS", "TVS Motor", "Auto", "NSE"),
    ("MOTHERSON.NS", "Samvardhana Motherson", "Auto Ancillary", "NSE"),
    ("SONACOMS.NS", "Sona BLW Precision", "Auto Ancillary", "NSE"),
    ("BALKRISIND.NS", "Balkrishna Industries", "Auto Ancillary", "NSE"),
    ("EXIDEIND.NS", "Exide Industries", "Auto Ancillary", "NSE"),
    ("BOSCHLTD.NS", "Bosch", "Auto Ancillary", "NSE"),
    ("MRF.NS", "MRF", "Auto Ancillary", "NSE"),
    ("AMARAJABAT.NS", "Amara Raja Energy", "Auto Ancillary", "NSE"),
    ("SUNDRMFAST.NS", "Sundram Fasteners", "Auto Ancillary", "NSE"),
    ("ENDURANCE.NS", "Endurance Technologies", "Auto Ancillary", "NSE"),
    ("SCHAEFFLER.NS", "Schaeffler India", "Auto Ancillary", "NSE"),
    ("CEATLTD.NS", "CEAT", "Auto Ancillary", "NSE"),
    ("FIVESTAR.NS", "Five-Star Business", "NBFC", "NSE"),
    ("CRAFTSMAN.NS", "Craftsman Automation", "Auto Ancillary", "NSE"),
    ("OLECTRA.NS", "Olectra Greentech", "Auto", "NSE"),
    ("JTEKTINDIA.NS", "JTEKT India", "Auto Ancillary", "NSE"),
    ("SUPRAJIT.NS", "Suprajit Engineering", "Auto Ancillary", "NSE"),
    ("GABRIEL.NS", "Gabriel India", "Auto Ancillary", "NSE"),

    # ── ENERGY & OIL/GAS (271-300) ─────────────────────────────────────
    ("HINDPETRO.NS", "Hindustan Petroleum", "Oil & Gas", "NSE"),
    ("PETRONET.NS", "Petronet LNG", "Oil & Gas", "NSE"),
    ("IGL.NS", "Indraprastha Gas", "Oil & Gas", "NSE"),
    ("MGL.NS", "Mahanagar Gas", "Oil & Gas", "NSE"),
    ("NHPC.NS", "NHPC", "Power", "NSE"),
    ("SJVN.NS", "SJVN", "Power", "NSE"),
    ("JSWENERGY.NS", "JSW Energy", "Power", "NSE"),
    ("TORNTPOWER.NS", "Torrent Power", "Power", "NSE"),
    ("CESC.NS", "CESC", "Power", "NSE"),
    ("RECLTD.NS", "REC", "Power", "NSE"),
    ("PFC.NS", "Power Finance Corp", "Power", "NSE"),
    ("IREDA.NS", "IREDA", "Power", "NSE"),
    ("TATAGREEN.NS", "Tata Technologies", "IT", "NSE"),
    ("ADANIPOWER.NS", "Adani Power", "Power", "NSE"),
    ("SUZLON.NS", "Suzlon Energy", "Power", "NSE"),
    ("INOXWIND.NS", "Inox Wind", "Power", "NSE"),
    ("JPPOWER.NS", "Jaiprakash Power", "Power", "NSE"),
    ("RELINFRA.NS", "Reliance Infra", "Infrastructure", "NSE"),
    ("OIL.NS", "Oil India", "Oil & Gas", "NSE"),
    ("MRPL.NS", "MRPL", "Oil & Gas", "NSE"),
    ("CASTROLIND.NS", "Castrol India", "Oil & Gas", "NSE"),
    ("GSPL.NS", "Gujarat State Petronet", "Oil & Gas", "NSE"),
    ("GUJGASLTD.NS", "Gujarat Gas", "Oil & Gas", "NSE"),
    ("ATGL.NS", "Adani Total Gas", "Oil & Gas", "NSE"),

    # ── CAPITAL GOODS & INFRASTRUCTURE (301-345) ───────────────────────
    ("CGPOWER.NS", "CG Power", "Capital Goods", "NSE"),
    ("TIINDIA.NS", "Tube Investments", "Engineering", "NSE"),
    ("THERMAX.NS", "Thermax", "Capital Goods", "NSE"),
    ("APLAPOLLO.NS", "APL Apollo Tubes", "Building Materials", "NSE"),
    ("SUPREMEIND.NS", "Supreme Industries", "Building Materials", "NSE"),
    ("ASTRAL.NS", "Astral", "Building Materials", "NSE"),
    ("POLYCAB.NS", "Polycab India", "Cables", "NSE"),
    ("KEI.NS", "KEI Industries", "Cables", "NSE"),
    ("PIIND.NS", "PI Industries", "Chemicals", "NSE"),
    ("ATUL.NS", "Atul", "Chemicals", "NSE"),
    ("NAVINFLUOR.NS", "Navin Fluorine", "Chemicals", "NSE"),
    ("DEEPAKNTR.NS", "Deepak Nitrite", "Chemicals", "NSE"),
    ("COCHINSHIP.NS", "Cochin Shipyard", "Defence", "NSE"),
    ("MAZAGONDOCK.NS", "Mazagon Dock", "Defence", "NSE"),
    ("GRSE.NS", "Garden Reach Shipbuilders", "Defence", "NSE"),
    ("BDL.NS", "Bharat Dynamics", "Defence", "NSE"),
    ("SOLARINDS.NS", "Solar Industries", "Defence", "NSE"),
    ("DATAPATTNS.NS", "Data Patterns", "Defence", "NSE"),
    ("HONAUT.NS", "Honeywell Automation", "Capital Goods", "NSE"),
    ("CERA.NS", "Cera Sanitaryware", "Building Materials", "NSE"),
    ("FINOLEX.NS", "Finolex Cables", "Cables", "NSE"),
    ("RATNAMANI.NS", "Ratnamani Metals", "Metals", "NSE"),
    ("KEC.NS", "KEC International", "Capital Goods", "NSE"),
    ("KALPATPOWR.NS", "Kalpataru Projects", "Capital Goods", "NSE"),
    ("IRB.NS", "IRB Infrastructure", "Infrastructure", "NSE"),
    ("NCC.NS", "NCC", "Infrastructure", "NSE"),
    ("NBCC.NS", "NBCC", "Infrastructure", "NSE"),
    ("ENGINERSIN.NS", "Engineers India", "Infrastructure", "NSE"),
    ("RVNL.NS", "Rail Vikas Nigam", "Infrastructure", "NSE"),
    ("IRCON.NS", "IRCON International", "Infrastructure", "NSE"),
    ("KPIL.NS", "Kalpataru Projects International", "Capital Goods", "NSE"),
    ("JKCEMENT.NS", "JK Cement", "Cement", "NSE"),
    ("RAMCOCEM.NS", "Ramco Cements", "Cement", "NSE"),
    ("DALMIA.NS", "Dalmia Bharat", "Cement", "NSE"),
    ("NUVAMA.NS", "Nuvama Wealth", "Financial Services", "NSE"),
    ("HAPPSTMNDS.NS", "Happiest Minds", "IT", "NSE"),
    ("JKLAKSHMI.NS", "JK Lakshmi Cement", "Cement", "NSE"),
    ("BIRLACEM.NS", "Birla Corporation", "Cement", "NSE"),
    ("HEIDELBERG.NS", "Heidelberg Cement", "Cement", "NSE"),
    ("PRISMJOINS.NS", "Prism Johnson", "Cement", "NSE"),
    ("CENTURYPLY.NS", "Century Plyboards", "Building Materials", "NSE"),
    ("GREENPLY.NS", "Greenply Industries", "Building Materials", "NSE"),
    ("JSWINFRA.NS", "JSW Infrastructure", "Infrastructure", "NSE"),
    ("SAGCEM.NS", "Sagar Cements", "Cement", "NSE"),

    # ── FMCG & CONSUMER (346-380) ──────────────────────────────────────
    ("EMAMILTD.NS", "Emami", "FMCG", "NSE"),
    ("JYOTHYLAB.NS", "Jyothy Labs", "FMCG", "NSE"),
    ("VGUARD.NS", "V-Guard Industries", "Consumer Durables", "NSE"),
    ("BLUESTARCO.NS", "Blue Star", "Consumer Durables", "NSE"),
    ("KAJARIACER.NS", "Kajaria Ceramics", "Building Materials", "NSE"),
    ("BATAINDIA.NS", "Bata India", "Footwear", "NSE"),
    ("RELAXO.NS", "Relaxo Footwears", "Footwear", "NSE"),
    ("METROBRAND.NS", "Metro Brands", "Footwear", "NSE"),
    ("DEVYANI.NS", "Devyani International", "QSR", "NSE"),
    ("JUBLFOOD.NS", "Jubilant Foodworks", "QSR", "NSE"),
    ("SAPPHIRE.NS", "Sapphire Foods", "QSR", "NSE"),
    ("UBL.NS", "United Breweries", "FMCG", "NSE"),
    ("UNITDSPR.NS", "United Spirits", "FMCG", "NSE"),
    ("RADICO.NS", "Radico Khaitan", "FMCG", "NSE"),
    ("VBL.NS", "Varun Beverages", "FMCG", "NSE"),
    ("BIKAJI.NS", "Bikaji Foods", "FMCG", "NSE"),
    ("PATANJALI.NS", "Patanjali Foods", "FMCG", "NSE"),
    ("DOMS.NS", "DOMS Industries", "Stationery", "NSE"),
    ("HONASA.NS", "Honasa Consumer (Mamaearth)", "FMCG", "NSE"),
    ("MAPMYINDIA.NS", "MapMyIndia", "IT", "NSE"),
    ("RAYMOND.NS", "Raymond", "Textiles", "NSE"),
    ("ARVIND.NS", "Arvind", "Textiles", "NSE"),
    ("MANYAVAR.NS", "Vedant Fashions", "Retail", "NSE"),
    ("SHOPERSTOP.NS", "Shoppers Stop", "Retail", "NSE"),
    ("VMART.NS", "V-Mart Retail", "Retail", "NSE"),
    ("ABFRL.NS", "Aditya Birla Fashion", "Retail", "NSE"),
    ("CAMPUS.NS", "Campus Activewear", "Footwear", "NSE"),
    ("ETHOS.NS", "Ethos", "Retail", "NSE"),

    # ── METALS, MINING & MATERIALS (381-410) ───────────────────────────
    ("SAIL.NS", "SAIL", "Metals", "NSE"),
    ("JINDALSTEL.NS", "Jindal Steel & Power", "Metals", "NSE"),
    ("HINDZINC.NS", "Hindustan Zinc", "Metals", "NSE"),
    ("MOIL.NS", "MOIL", "Mining", "NSE"),
    ("WELCORP.NS", "Welspun Corp", "Metals", "NSE"),
    ("AARTIPHARM.NS", "Aarti Pharmalabs", "Pharma", "NSE"),
    ("FLUOROCHEM.NS", "Gujarat Fluorochemicals", "Chemicals", "NSE"),
    ("NOCIL.NS", "NOCIL", "Chemicals", "NSE"),
    ("ANANTRAJ.NS", "Anant Raj", "Real Estate", "NSE"),
    ("BRIGADE.NS", "Brigade Enterprises", "Real Estate", "NSE"),
    ("SOBHA.NS", "Sobha", "Real Estate", "NSE"),
    ("SUNTECK.NS", "Sunteck Realty", "Real Estate", "NSE"),
    ("PHOENIXLTD.NS", "Phoenix Mills", "Real Estate", "NSE"),
    ("LODHA.NS", "Macrotech Developers", "Real Estate", "NSE"),
    ("SIGNATURE.NS", "Signature Global", "Real Estate", "NSE"),
    ("APARINDS.NS", "Apar Industries", "Capital Goods", "NSE"),
    ("PPLPHARMA.NS", "Piramal Pharma", "Pharma", "NSE"),
    ("KALYANKJIL.NS", "Kalyan Jewellers", "Consumer Durables", "NSE"),
    ("SENCO.NS", "Senco Gold", "Consumer Durables", "NSE"),
    ("GOLDIAM.NS", "Goldiam International", "Consumer Durables", "NSE"),

    # ── DIVERSIFIED / OTHERS (411-500) ─────────────────────────────────
    ("HINDPETRO.NS", "Hindustan Petroleum", "Oil & Gas", "NSE"),
    ("TATATECH.NS", "Tata Technologies", "IT", "NSE"),
    ("BERGEPAINT.NS", "Berger Paints", "Paints", "NSE"),
    ("KANSAINER.NS", "Kansai Nerolac", "Paints", "NSE"),
    ("AKZOINDIA.NS", "Akzo Nobel India", "Paints", "NSE"),
    ("INDHOTEL.NS", "Indian Hotels", "Hospitality", "NSE"),
    ("LEMONTREE.NS", "Lemon Tree Hotels", "Hospitality", "NSE"),
    ("CHALET.NS", "Chalet Hotels", "Hospitality", "NSE"),
    ("EIHOTEL.NS", "EIH", "Hospitality", "NSE"),
    ("THOMASCOOK.NS", "Thomas Cook India", "Travel", "NSE"),
    ("EASEMYTRIP.NS", "Easy Trip Planners", "Travel", "NSE"),
    ("YATRA.NS", "Yatra Online", "Travel", "NSE"),
    ("CRISIL.NS", "CRISIL", "Financial Services", "NSE"),
    ("ICRA.NS", "ICRA", "Financial Services", "NSE"),
    ("CARERATING.NS", "CARE Ratings", "Financial Services", "NSE"),
    ("GNFC.NS", "GNFC", "Chemicals", "NSE"),
    ("GSFC.NS", "GSFC", "Chemicals", "NSE"),
    ("DCMSHRIRAM.NS", "DCM Shriram", "Chemicals", "NSE"),
    ("TATAINVEST.NS", "Tata Investment Corp", "Financial Services", "NSE"),
    ("SWANENERGY.NS", "Swan Energy", "Diversified", "NSE"),
    ("ISEC.NS", "ICICI Securities", "Financial Services", "NSE"),
    ("JBMA.NS", "JBM Auto", "Auto Ancillary", "NSE"),
    ("TITAGARH.NS", "Titagarh Rail Systems", "Capital Goods", "NSE"),
    ("TEXRAIL.NS", "Texmaco Rail", "Capital Goods", "NSE"),
    ("RITES.NS", "RITES", "Infrastructure", "NSE"),
    ("RAILTEL.NS", "RailTel Corporation", "IT", "NSE"),
    ("CONCOR.NS", "Container Corp", "Logistics", "NSE"),
    ("DELHIVERY.NS", "Delhivery", "Logistics", "NSE"),
    ("ALLCARGO.NS", "Allcargo Logistics", "Logistics", "NSE"),
    ("BLUEJET.NS", "Blue Jet Healthcare", "Pharma", "NSE"),
    ("JYOTICNC.NS", "Jyoti CNC Automation", "Capital Goods", "NSE"),
    ("IIFLSEC.NS", "IIFL Securities", "Financial Services", "NSE"),
    ("UJJIVANSFB.NS", "Ujjivan Small Finance Bank", "Banking", "NSE"),
    ("EQUITASBNK.NS", "Equitas Small Finance Bank", "Banking", "NSE"),
    ("UTIAMC.NS", "UTI AMC", "Financial Services", "NSE"),
    ("FINCABLES.NS", "Finolex Cables", "Cables", "NSE"),
    ("POWERINDIA.NS", "Hitachi Energy India", "Capital Goods", "NSE"),
    ("TRIVENI.NS", "Triveni Turbine", "Capital Goods", "NSE"),
    ("ELECON.NS", "Elecon Engineering", "Capital Goods", "NSE"),
    ("AAVAS.NS", "Aavas Financiers", "NBFC", "NSE"),
    ("HOMEFIRST.NS", "Home First Finance", "NBFC", "NSE"),
    ("STARHEALTH.NS", "Star Health Insurance", "Insurance", "NSE"),
    ("TATACOMM.NS", "Tata Communications", "Telecom", "NSE"),
    ("SUNTV.NS", "Sun TV Network", "Media", "NSE"),
    ("PVR.NS", "PVR INOX", "Media", "NSE"),
    ("NETWEB.NS", "Netweb Technologies", "IT", "NSE"),
    ("LATENTVIEW.NS", "Latent View Analytics", "IT", "NSE"),
    ("INDIGOPNTS.NS", "Indigo Paints", "Paints", "NSE"),
    ("AADHARHFC.NS", "Aadhar Housing Finance", "NBFC", "NSE"),
    ("360ONE.NS", "360 ONE WAM", "Financial Services", "NSE"),
    ("AEGISCHEM.NS", "Aegis Logistics", "Oil & Gas", "NSE"),
    ("GPIL.NS", "Godawari Power & Ispat", "Metals", "NSE"),
    ("LLOYDSME.NS", "Lloyds Metals & Energy", "Metals", "NSE"),
    ("BSOFT.NS", "BIRLASOFT", "IT", "NSE"),
    ("ZYDUSLIFE.NS", "Zydus Lifesciences", "Pharma", "NSE"),
    ("TORNTPHARM.NS", "Torrent Pharma", "Pharma", "NSE"),
    ("SUNCLAYERG.NS", "Sundaram Clayton", "Auto Ancillary", "NSE"),
    ("MAZDOCK.NS", "Mazagon Dock", "Defence", "NSE"),
    ("HFCL.NS", "HFCL", "Telecom", "NSE"),
    ("PRAJIND.NS", "Praj Industries", "Capital Goods", "NSE"),
    ("SUVENPHAR.NS", "Suven Pharma", "Pharma", "NSE"),
]
